### ISSUE TITLE
Golang webserver hello world

### ISSUE THREAD

**Issue by itimofeev** [OlegTimofeev/QueryProcessing#1]
Нужно погуглить, как на Go запустить свой вебсервер на порту 8080 например + написать свой обработчик запросов, который бы возвращал "hello, world", когда в браузере открываешь страничку http://localhost:8080/

**Comment by OlegTimofeev** [comment]
Сервер работает, при открытии http://localhost:8080/ вывод сообщения Hello from Web Server in Go.
